# Generated by Django 5.2 on 2025-04-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_rename_file_video_video_remove_video_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('image', models.ImageField(default='images/default.png', upload_to='support/images/')),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
