# Generated by Django 5.2 on 2025-04-26 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='support',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='erp.support'),
        ),
    ]
